### ISSUE TITLE
macOS configuration compared to Migration Assistant

### ISSUE THREAD

**Issue by chrisothal** [bkuhlmann/mac_os#3]
I have a (seemingly ignorant) question. How does this setup compare to OS X's Migration Assistant assuming you are perfectly happy with your current machine setup? Is there a particular reason you prefer having a scripted setup?

**Comment by bkuhlmann** [comment]
Yeah, good question. There are several reasons, actually:

- Reduces the amount of cruft carried over from Migration Assistant (MA). MA does a good job of getting you back up and running but will also carry over baggage that you may or may not need any longer.
- These scripts are handy for new machine setups where you might want a new machine (or several machines) configured with an identical configuration that is a little easier to automate than using MA.
- On the flipside, these scripts can be easily cloned to setup multiple machines with slightly different configurations. This can be handy for a DevOps situation, where you need to manage an army of machines for a team or client(s).
- It's nice being able to know how your machine is configured so that if anyone goes wrong, you know what to fix. This knowledge is also useful for keeping your machine upgraded too.

**Comment by bkuhlmann** [comment]
Closing this issue due to no further feedback.
